### PR TITLE
make sort() can also work when reading connection table

### PR DESCRIPTION
**Pull request by ap9994405**
using parameter pah%initiallabel save new order of carbon atom in sort.f90
based on changing in sort.f90, using newlabel = pah%initiallabel(oldlabel) at line 121,122 in input.f90

### CODE REVIEW

**Comment by quantumint** [comment]
Clever use of (previously unused) initiallabel). 

But there are two related issues:

1. `if (.not. unsorted_geometry)` is gone and the code always sorts. It has to be brought back.
2. `initiallabel` is initialized in sort and it needs to be initialized before sort

 Also, the indentation around "find neighbor table" is changed and the commit looks bigger than it should. I would rather see it as a separate commit.

**Comment by ap9994405** [comment]
1. if (.not. unsorted_geometry) is brought back now
2. pah%initiallabel is now initialized outside the sort() function. Additionally, the change of indentation around 'find neighbor table' is the same as previous version.
3. Added details to -X option in README.md

**Comment by quantumint** [comment]
It looks good now. Please change the README description to:

The -X option causes ZZPolyCalc to bypass the default generation of connectivity tables and instead read a connectivity table appended to the bottom of the XYZ file. Unless the '-u' option is also used, the atom order is determined by sorting the z, y, and x coordinates, and the connectivity list is then remapped to correspond to the sorted XYZ file. The '-u' option ensures compatibility with ZZCalculator but the default sorting is recommended. The format of the connectivity table is as follows:

Also, add comment "! replace with the reverse map"
after  initiallabel = tmpinitiallabel in sort.f90

**Comment by ap9994405** [comment]
1.  Change the description of -X option in README
2.  Add comment after initiallabel = tmpinitiallabel (line 35) in sort.f90

**Pull request merged**
